/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/renderer/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Design System – Semantic Colors
        background: "#09090b",
        surface: {
          DEFAULT: "#131315",
          dim: "#131315",
          bright: "#39393b",
          "container-lowest": "#0e0e10",
          "container-low": "#1c1b1d",
          container: "#201f22",
          "container-high": "#2a2a2c",
          "container-highest": "#353437",
          variant: "#353437",
          tint: "#c0c1ff",
        },
        "on-surface": {
          DEFAULT: "#e5e1e4",
          variant: "#c6c4d8",
        },
        "on-background": "#e5e1e4",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        primary: {
          DEFAULT: "#c0c1ff",
          container: "#5b5fff",
          fixed: "#e1e0ff",
          "fixed-dim": "#c0c1ff",
        },
        "on-primary": {
          DEFAULT: "#0d00aa",
          container: "#fffcff",
          fixed: "#05006c",
          "fixed-variant": "#2623d1",
        },
        "inverse-primary": "#4345e8",
        secondary: {
          DEFAULT: "#d2bbff",
          container: "#6001d1",
          fixed: "#eaddff",
          "fixed-dim": "#d2bbff",
        },
        "on-secondary": {
          DEFAULT: "#3f008e",
          container: "#c9aeff",
          fixed: "#25005a",
          "fixed-variant": "#5a00c6",
        },
        tertiary: {
          DEFAULT: "#2fd9f4",
          container: "#008092",
          fixed: "#a2eeff",
          "fixed-dim": "#2fd9f4",
        },
        "on-tertiary": {
          DEFAULT: "#00363e",
          container: "#f7fdff",
          fixed: "#001f25",
          "fixed-variant": "#004e5a",
        },
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        "on-error": {
          DEFAULT: "#690005",
          container: "#ffdad6",
        },
        outline: {
          DEFAULT: "#908fa1",
          variant: "#454555",
        },
        // Legacy token aliases
        "error-container": "#93000a",
        "surface-bright": "#39393b",
        "tertiary-container": "#008092",
        "on-error-container": "#ffdad6",
        "primary-container": "#5b5fff",
        "on-primary-container": "#fffcff",
        "secondary-container": "#6001d1",
        "on-secondary-container": "#c9aeff",
        "on-tertiary-container": "#f7fdff",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "surface-container-low": "#1c1b1d",
        "surface-container-lowest": "#0e0e10",
        "surface-container": "#201f22",
        "surface-dim": "#131315",
        "surface-variant": "#353437",
        "surface-tint": "#c0c1ff",
        "on-surface-variant": "#c6c4d8",
        "inverse-primary": "#4345e8",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        "outline-variant": "#454555",
      },
      fontFamily: {
        rubik: ["var(--font-rubik)", "Rubik", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-xs": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        base: "4px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-xl": "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "12px",
        "2xl": "24px",
        "3xl": "32px",
        full: "9999px",
      },
      boxShadow: {
        glow: "0px 0px 20px rgba(91, 95, 255, 0.3)",
        "glow-lg": "0px 0px 30px rgba(91, 95, 255, 0.5)",
        "glow-sm": "0px 0px 15px rgba(91, 95, 255, 0.2)",
        glass: "0 8px 32px 0 rgba(0, 0, 0, 0.37)",
        ambient: "0 0 40px rgba(91, 95, 255, 0.15)",
      },
      animation: {
        "text-shine": "text-shine 4s linear infinite",
        float: "float 5s ease-in-out infinite",
        "pulse-glow": "pulse-glow 6s ease-in-out infinite",
      },
      keyframes: {
        "text-shine": {
          "0%": { backgroundPosition: "0% 50%" },
          "100%": { backgroundPosition: "200% 50%" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.15", transform: "scale(1)" },
          "50%": { opacity: "0.3", transform: "scale(1.05)" },
        },
      },
    },
  },
  plugins: [],
};
